language: node_js
node_js:
  - 12.13
cache:
  directories:
    - node_modules
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "gatsby build"
after_success:
  - "build completed successfully"
